/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2024-09-11 12:55:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Antivirus Mask Store</title>\r\n");
      out.write("    <!-- icon -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"shortcut icon\"\r\n");
      out.write("      href=\"./assets/images/logo.png\"\r\n");
      out.write("      type=\"image/x-icon\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- reset css -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css\"\r\n");
      out.write("      integrity=\"sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("      referrerpolicy=\"no-referrer\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- font awesome -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("      integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("      referrerpolicy=\"no-referrer\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- base -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/base.css\" />\r\n");
      out.write("    <!-- style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/style.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("      <div class=\"top-header\">\r\n");
      out.write("        Due to the COVID 19 epidemic, orders may be processed with a slight\r\n");
      out.write("        delay\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header-main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"inner-wrap\">\r\n");
      out.write("            <div class=\"inner-logo\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"./assets/images/logo.png\" alt=\"\" />\r\n");
      out.write("                <span>CureM4</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-menu\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Shop</a></li>\r\n");
      out.write("                <li><a href=\"#\">Products</a></li>\r\n");
      out.write("                <li><a href=\"#\">About</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-contact\">Need help? 989-879-0847</div>\r\n");
      out.write("            <div class=\"inner-social\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-bars\">\r\n");
      out.write("              <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- end header -->\r\n");
      out.write("    <!-- section one -->\r\n");
      out.write("    <div class=\"section-one\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-content\">\r\n");
      out.write("            <h1 class=\"inner-title\">\r\n");
      out.write("              Antivirus <br />\r\n");
      out.write("              Mask Store\r\n");
      out.write("            </h1>\r\n");
      out.write("            <div class=\"inner-desc\">The easiest way to protect yourself</div>\r\n");
      out.write("            <div class=\"inner-list\">\r\n");
      out.write("              <div class=\"inner-item\">\r\n");
      out.write("                <i class=\"fa-solid fa-shield\"></i>\r\n");
      out.write("\r\n");
      out.write("                <span>Anti-Bacterial</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-item\">\r\n");
      out.write("                <i class=\"fa-solid fa-globe\"></i>\r\n");
      out.write("\r\n");
      out.write("                <span> Anti-Virus</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"button-shop-now\"\r\n");
      out.write("              >Shop now\r\n");
      out.write("              <span class=\"space-transit\"></span>\r\n");
      out.write("              <i class=\"fa-solid fa-chevron-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-image\">\r\n");
      out.write("            <img src=\"./assets/images/product1.jpg\" alt=\"\" />\r\n");
      out.write("            <div class=\"inner-sale\">\r\n");
      out.write("              <span>only</span>\r\n");
      out.write("              <span class=\"price\">$25</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section one -->\r\n");
      out.write("    <!-- section two -->\r\n");
      out.write("    <div class=\"section-two\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-box\">\r\n");
      out.write("            <img src=\"./assets/images/mbr.jpg\" alt=\"\" />\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("              <span class=\"tag-new\">NEW</span>\r\n");
      out.write("              <h2 class=\"inner-title\">\r\n");
      out.write("                Antivirus <br />\r\n");
      out.write("                Mask\r\n");
      out.write("              </h2>\r\n");
      out.write("              <a href=\"\" class=\"inner-button\">More</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-box\">\r\n");
      out.write("            <img src=\"./assets/images/card1.jpg\" alt=\"\" />\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("              <h2 class=\"inner-title\">Basic <br />Mask</h2>\r\n");
      out.write("              <span class=\"tag-sale\">-30%</span>\r\n");
      out.write("              <br />\r\n");
      out.write("              <a href=\"\" class=\"inner-button\">Shop now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-box\">\r\n");
      out.write("            <img src=\"./assets/images/mbr-3.jpg\" alt=\"\" />\r\n");
      out.write("            <div class=\"inner-content\">\r\n");
      out.write("              <h2 class=\"inner-title\">Medical Mask</h2>\r\n");
      out.write("              <span class=\"new-price\">$15.99</span>\r\n");
      out.write("              <br />\r\n");
      out.write("              <del class=\"old-price\">$29.99</del>\r\n");
      out.write("              <br />\r\n");
      out.write("              <a href=\"\" class=\"inner-button\">Buy now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section two -->\r\n");
      out.write("    <!-- section three -->\r\n");
      out.write("    <div class=\"section-three\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-head\">\r\n");
      out.write("            <h2 class=\"inner-title\">\r\n");
      out.write("              Effective and reliable\r\n");
      out.write("              <br />\r\n");
      out.write("              protection for your\r\n");
      out.write("            </h2>\r\n");
      out.write("            <p class=\"inner-desc\">\r\n");
      out.write("              Lorem ipsum dolor sit amet consectetur, adipisicing elit.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-list-items\">\r\n");
      out.write("            <div class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-image\">\r\n");
      out.write("                <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h3 class=\"inner-name\">Loremisump</h3>\r\n");
      out.write("                <p class=\"inner-desc\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, <br />\r\n");
      out.write("                  consectetur adipisicing.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-item\">\r\n");
      out.write("              <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("              <h3 class=\"inner-name\">Loremisump</h3>\r\n");
      out.write("              <p class=\"inner-desc\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, <br />\r\n");
      out.write("                consectetur adipisicing.\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-item\">\r\n");
      out.write("              <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("              <h3 class=\"inner-name\">Loremisump</h3>\r\n");
      out.write("              <p class=\"inner-desc\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, <br />\r\n");
      out.write("                consectetur adipisicing.\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section three -->\r\n");
      out.write("    <!-- section four -->\r\n");
      out.write("    <div class=\"section-four\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-content\">\r\n");
      out.write("            <h2 class=\"inner-title\">Effective & reliable protection</h2>\r\n");
      out.write("            <div class=\"inner-desc\">\r\n");
      out.write("              Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("            </div>\r\n");
      out.write("            <button href=\"#\" class=\"btn-about\">About</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-img\">\r\n");
      out.write("            <img src=\"./assets/images/features1.jpg\" alt=\"\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section four -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section five -->\r\n");
      out.write("    <div class=\"section-five\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-img\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/background23.jpg\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-content\">\r\n");
      out.write("            <div class=\"inner-desc\">\r\n");
      out.write("              <i class=\"fa-solid fa-shield\"></i>\r\n");
      out.write("              Secure delivery without contacting the courier\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"inner-button\">More</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section five -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section six -->\r\n");
      out.write("    <div class=\"section-six\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <h2 class=\"inner-title\">Featured products</h2>\r\n");
      out.write("          <div class=\"inner-list\">\r\n");
      out.write("            <a class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-img\">\r\n");
      out.write("                <img src=\"./assets/images/features2.jpg\" alt=\"\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h4 class=\"inner-name\">Basic Mask</h4>\r\n");
      out.write("                <h4 class=\"price\">$1.99</h4>\r\n");
      out.write("                <div class=\"inner-list-star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-img\">\r\n");
      out.write("                <img src=\"./assets/images/features2.jpg\" alt=\"\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h4 class=\"inner-name\">Basic Mask</h4>\r\n");
      out.write("                <h4 class=\"price\">$1.99</h4>\r\n");
      out.write("                <div class=\"inner-list-star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-img\">\r\n");
      out.write("                <img src=\"./assets/images/features2.jpg\" alt=\"\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h4 class=\"inner-name\">Basic Mask</h4>\r\n");
      out.write("                <h4 class=\"price\">$1.99</h4>\r\n");
      out.write("                <div class=\"inner-list-star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-img\">\r\n");
      out.write("                <img src=\"./assets/images/features2.jpg\" alt=\"\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h4 class=\"inner-name\">Basic Mask</h4>\r\n");
      out.write("                <h4 class=\"price\">$1.99</h4>\r\n");
      out.write("                <div class=\"inner-list-star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"inner-item\">\r\n");
      out.write("              <div class=\"inner-img\">\r\n");
      out.write("                <img src=\"./assets/images/features2.jpg\" alt=\"\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                <h4 class=\"inner-name\">Basic Mask</h4>\r\n");
      out.write("                <h4 class=\"price\">$1.99</h4>\r\n");
      out.write("                <div class=\"inner-list-star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- section six -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section seven -->\r\n");
      out.write("    <div class=\"section-seven\">\r\n");
      out.write("      <h2 class=\"inner-title\">\r\n");
      out.write("        Join our newsletter and\r\n");
      out.write("        <br />\r\n");
      out.write("        get $20 discount\r\n");
      out.write("      </h2>\r\n");
      out.write("      <div class=\"inner-leave-mail\">\r\n");
      out.write("        <input\r\n");
      out.write("          class=\"inner-mail\"\r\n");
      out.write("          placeholder=\"Enter your email address\"\r\n");
      out.write("          type=\"email\"\r\n");
      out.write("        />\r\n");
      out.write("        <a href=\"#\" class=\"inner-button-subscribe\">Subscribe</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section seven -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section eight -->\r\n");
      out.write("    <div class=\"section-eight\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <h2 class=\"inner-title text-center mt-5 mb-5 text-primary\">\r\n");
      out.write("            Watch Video\r\n");
      out.write("          </h2>\r\n");
      out.write("          <div class=\"inner-video\">\r\n");
      out.write("            <iframe\r\n");
      out.write("              src=\"https://www.youtube.com/embed/VA8PzkQa8d8?si=KBUpC-9LYzO4l7h1\"\r\n");
      out.write("              title=\"YouTube video player\"\r\n");
      out.write("              frameborder=\"0\"\r\n");
      out.write("              allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\r\n");
      out.write("              referrerpolicy=\"strict-origin-when-cross-origin\"\r\n");
      out.write("              allowfullscreen\r\n");
      out.write("            ></iframe>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section eight -->\r\n");
      out.write("    <!-- section nine -->\r\n");
      out.write("    <div class=\"section-nine\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <h2 class=\"inner-title\">\r\n");
      out.write("            <i class=\"fa-solid fa-quote-right\"></i>Latest reviews\r\n");
      out.write("          </h2>\r\n");
      out.write("          <div class=\"inner-list\">\r\n");
      out.write("            <div class=\"inner-box\">\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce\r\n");
      out.write("                facilisis diam at libero aliquam, sed vestibulum elit feugiat.\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"inner-writer\">John Smith</h5>\r\n");
      out.write("              <div class=\"inner-star\">\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-box\">\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce\r\n");
      out.write("                facilisis diam at libero aliquam, sed vestibulum elit feugiat.\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"inner-writer\">John Smith</h5>\r\n");
      out.write("              <div class=\"inner-star\">\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-box\">\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce\r\n");
      out.write("                facilisis diam at libero aliquam, sed vestibulum elit feugiat.\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"inner-writer\">John Smith</h5>\r\n");
      out.write("              <div class=\"inner-star\">\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-box\">\r\n");
      out.write("              <div class=\"inner-content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce\r\n");
      out.write("                facilisis diam at libero aliquam, sed vestibulum elit feugiat.\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5 class=\"inner-writer\">John Smith</h5>\r\n");
      out.write("              <div class=\"inner-star\">\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section nine -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section ten -->\r\n");
      out.write("    <div class=\"section-ten\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-contact\">\r\n");
      out.write("            <div class=\"inner-top\">\r\n");
      out.write("              <h2 class=\"inner-title\">How can we help you?</h2>\r\n");
      out.write("              <p class=\"inner-desc\">We are at your disposal 7 days a week!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-between\">\r\n");
      out.write("              <h2 class=\"inner-phone-number\">989-879-0847</h2>\r\n");
      out.write("              <p class=\"work-schedule\">\r\n");
      out.write("                Monday – Friday: 9:00-20:00 <br />\r\n");
      out.write("                Saturday: 11:00 – 15:00\r\n");
      out.write("              </p>\r\n");
      out.write("              <a class=\"inner-btn-mail\"> contact@yoursite.com </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-social\">\r\n");
      out.write("              <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("              <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("              <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("              <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-map\">\r\n");
      out.write("            <iframe\r\n");
      out.write("              src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3022.6066536470325!2d-73.986431!3d40.74868!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259a9b30eac9f%3A0xaca05ca48ab5ac2c!2s350%205th%20Ave%2C%20New%20York%2C%20NY%2010118!5e0!3m2!1sen!2sus!4v1725518963847!5m2!1sen!2sus\"\r\n");
      out.write("              width=\"90%\"\r\n");
      out.write("              height=\"100%\"\r\n");
      out.write("              style=\"border: 0\"\r\n");
      out.write("              allowfullscreen=\"\"\r\n");
      out.write("              loading=\"lazy\"\r\n");
      out.write("              referrerpolicy=\"no-referrer-when-downgrade\"\r\n");
      out.write("            ></iframe>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section ten -->\r\n");
      out.write("\r\n");
      out.write("    <!-- section eleven -->\r\n");
      out.write("    <div class=\"section-eleven\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <div class=\"inner-item\">\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-item\">\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-item\">\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-item\">\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"inner-item\">\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("            <p>lorem</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end section eleven -->\r\n");
      out.write("    <footer class=\"copyright\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <h3 class=\"inner-text\">\r\n");
      out.write("            Copyright 2025 Mobirise. All Rights Reserved\r\n");
      out.write("          </h3>\r\n");
      out.write("          <div class=\"inner-logo\">\r\n");
      out.write("            <img\r\n");
      out.write("              class=\"image\"\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/master-card.png\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <img\r\n");
      out.write("              class=\"image\"\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/master-card.png\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <img\r\n");
      out.write("              class=\"image\"\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/master-card.png\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <img\r\n");
      out.write("              class=\"image\"\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/master-card.png\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <img\r\n");
      out.write("              class=\"image\"\r\n");
      out.write("              src=\"https://mobirise.com/extensions/curem4/mask-store/assets/images/master-card.png\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
